### ISSUE TITLE
Programmatically pushing nodes to branchnodes requires update of numNodes property

### ISSUE THREAD

**Issue by EnricoPietrocola** [Calamari/BehaviorTree.js#48]
I discovered that pushing nodes in a blueprint in order to programmatically populate blueprints/branches will not properly execute unless you increment the numNodes property of the object. 
Example code below, without mainSequence.numNodes++ I couldn't get steps working, they didn't see the nodes at all. 
Is this an undefined behavior or is there a function I should be using instead?

```
const { BehaviorTree, Sequence, Task, Selector, SUCCESS, FAILURE, RUNNING, decorators: {InvertDecorator}, Decorator} = require('behaviortree')
const NanoTimer = require('nanotimer');
const timer = new NanoTimer();

function NoteTask(note = 60, velocity = 100) {
    return new Task({
        start: function (blackboard) {
            blackboard.isStarted = true;
            console.log("NOTE " + this.note)
        },
        end: function (blackboard) {
            blackboard.isStarted = false;
            blackboard.deltaTime = 0;
        },
        run: function (blackboard) {
            return SUCCESS
        },
        note: note,
        velocity: velocity,
    })
}

let deltaTime = {
    deltaTime: 0
};


const mainSequence = new Sequence({
    nodes: []
})


if(mainSequence.blueprint.nodes == null){
   // mainSequence.blueprint.nodes = []
}
mainSequence.blueprint.nodes.push(NoteTask(60))
mainSequence.numNodes++
mainSequence.blueprint.nodes.push(NoteTask(69))
mainSequence.numNodes++
console.log(mainSequence)

let bTree = new BehaviorTree({
    tree: mainSequence,
    blackboard: deltaTime
})

//console.log(mainSequence)

timer.setTimeout(loop, '', '1000m')

function loop() {
    bTree.step()
    timer.setTimeout(loop,'',  "400m");
}

loop();


```

**Comment by Calamari** [comment]
Interesting. I am not quite sure if making a BehaviorTree dynamic in that way, that you push in, remove or alter nodes in an defined tree. I have to think about this a bit.

Though, my first thoughts on this are: The BTree is a way in games for defining the NPC logic so a game designer (who might not be a programmer at all) can define a structure for the NPC’s AI and can reason about it through the structure he defined and the components (Sequences, Selectors, Nodes & Decorators) he uses. I guess it will get really hard to reason about and debug the BehaviorTree one just created when it also can change. 
If you want some parts of the tree be switched of or only to activate when some conditions are met, there are better ways of dynamically change the tree. You can use decorators to make those parts of the tree work or not depending on the environment.

That being said, I am always open to more reasons why someone want to dynamically update the tree. And I will certainly think further on it as well.

**Comment by EnricoPietrocola** [comment]
I absolutely agree with you on the use case of a behavior tree. The issue actually came up not because of I'm changing the bt in play time, but because I have my GUI nodes responsible to populate the tree once I'm over designing it. I have a GUI Root object instantiating a Selector, then I call the connected GUI children to the GUI Root, and they add themselves in their respective BehaviorTree classes to that Selector and so on in some sort of recursive fashion (I'm no totally sure I could define this behavior as recursive). 
With this logic, at build time of the tree, I have to dynamically add nodes as children to other nodes. And it didn't work as long as I didn't change the numNodes property accordingly. BTree steps but doesn't go through those nodes.

That said, I would agree there is no need for a fix for this, as it's not really a bug and not really in design with behavior trees, but I think you could mention this in the Readme for future people who do something like I did and can't figure out why their nodes are not being reached by steps :)

Another behavior I wasn't expecting, is that a BehaviorTree.tree property in which you assign your whole tree, seems to grab the tree by value and not by reference. Therefore every time I change a tree and reset things, I have to instantiate a whole new BTree.
But I guess this is actually wanted because of introspection, right?

Anyway, I just wanted to ping this information for future reference so that if anyone starts exploring (and abusign like me ;D ) this library won't need to go through the same way I did
