### ISSUE TITLE
Node.js constructor: use original user parameter instead of destructuring

### ISSUE THREAD

**Issue by Joe-Kerr** [Calamari/BehaviorTree.js#50]
Hi,

Is there any chance for the following change?

(https://github.com/Calamari/BehaviorTree.js/blob/fefd459ae03c5afd237d4d392dcaf58cd63da568/src/Node.js#L8)

to something like

```javascript
  constructor(setup) {
    setup.run = setup.run || NOOP;
    setup.start = setup.start || NOOP;
    setup.end = setup.end || NOOP;  
    this.blueprint = setup;
  }
```

This would have the advantage that User can pass in a class instance while preserving the class context. E.g.

```javascript
class MyAction {
    
    myMethod() {/*...*/}

    run() {
         this.myMethod() //currently throws "myMethod is not a function"
    }
}

BehaviorTree.register("myAction", new Task( new MyAction() ));
```

**Comment by Calamari** [comment]
Hi, thanks for the interest.

I am trying to understand what you want to achieve with this. Do I get it right that the main purpose is to be able to make the blueprint an instance of a class, so you can call methods on it?

Why don't you let MyAction inherit from Task directly and just pass an instance of this to the BTree?

On the first glance, it feels weird to pass in a thing called blueprint to make it work as something that should be solved as inheritance. But I am also not quite sure, if I totally get the problem/use case.

**Comment by Joe-Kerr** [comment]
Nevermind, does not work as I thought it would. I aplogise for the inconvenience.

**Comment by Calamari** [comment]
No worries :-)
