### ISSUE TITLE
Unneeded dependencies

### ISSUE THREAD

**Issue by antoinemacia** [Calamari/BehaviorTree.js#52]
Hello!

First thing first, love your work! I love the simplicity of this lib, minimal and easy to use, bravo!

One thing I noticed is some of the required dependencies are mostly dev stuff, but definitely weight big on production builds 
 
```
    "core-js": "^3.11.1",
    "eslint-config-prettier": "^8.2.0",
    "eslint-plugin-prettier": "^3.4.0",
    "prettier": "^2.2.1"
```

[Prettier](https://bundlephobia.com/package/prettier@2.3.2) on its own is fatso and definitely not a need in production

The only one that fits here is core-js, but I'm curious what are the polyfills you are using? Bringing them individually would also bring the bundle size seriously

I might be wrong, but Im sure a lot of the apps that would use this lib would be games, which are all performance bound - removing unnecessary deps would make this lib more attractive (or not needed to be forked)

Keen to hear your thoughts!

**Comment by antoinemacia** [comment]
@Calamari would love to make a PR for it if you welcome them!

**Comment by Calamari** [comment]
Sorry, was on vacation. :-)
Sure, go ahead, I totally welcome PRs. And I agree, that those deps probably are not needed for any sensible production build.
