### ISSUE TITLE
S-expression parser

### ISSUE THREAD

**Issue by noffle** [Calamari/BehaviorTree.js#7]
Hi there! Thanks for writing this great little module. I put together [an S-expression parser](https://github.com/noffle/behaviortree-sexp) for it for my own uses, and figured I'd give you a heads up. Cheers!

**Comment by Calamari** [comment]
I love it. Nice way of defined such a tree. I thought at some point writing a small GUI app, that allowe you to define such a tree via Drag'n'Drop, but didn't had the time too.

But this really looks a neat thing, that is somewhat more readable than having them in code pure. I think I will open up a Tools section in the Readme and feature it there :)

**Comment by noffle** [comment]
Thanks! I very quickly became exhausted at writing trees in code, so this was the next easiest thing. A web editor would be really nice though -- especially if you could plug different behaviour tree backend modules into it (yours being one, natch).

**Comment by Calamari** [comment]
I think the problem with having one editor for different behaviour tree implementations is that different implementations have different interfaces. The is no common general interface I am aware of at least. But this could be an interesting research topic.
