### ISSUE TITLE
Which file should I add?

### ISSUE THREAD

**Issue by lcd78706** [Calamari/BehaviorTree.js#8]
@Calamari 
Hi, I am a member of cdnjs project and I want to add this library.
But I don't know the file I should add is "btree-complete.js" or "src/behavior_tree.js".
I want to confirm with you.

https://github.com/cdnjs/cdnjs/issues/10164

**Comment by Calamari** [comment]
Hi! 

I think it depends on what you want to achieve. The files in the `src`-folder have to go through browserify to be usable ES5 code. But as the `package.json` states the `btree-complete.js` is the main file that is already directly embeddable in HTML. You could also use `btree-complete.min.js` if you prefer a already minified build.

hope that helps. If not just say it :)

**Comment by lcd78706** [comment]
Thanks a lot!
